# Setup
title: "Re:L"
url: https://ikkifik.github.io/
# paginate: 1
baseurl: ""
permalink: /:categories/:year/:month/:day/:title

# Gems
plugins:
  - jekyll-gist
  # - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-Y0RK875LY8

# Specify the author for blog posts
author:
  name: Ikkifik
  url: zuhdifikri.my.id
  email: mzfikrij@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
# TODO: create sublink https://mycyberuniverse.com/jekyll-bootstrap-dynamic-navigation-highlighting-active-element.html
nav:
  - title: Artikel
    url: /articles
  - title: Project
    url: /project
  # - title: Agenda
  #   url: /agenda
  # - title: Buku
  #   url: /books
  # - title: Lainnya
  #   sublinks:
  #     - title: Buku
  #       url: /books
  #     - title: Tentang
  #       url: /about

collections:
  notes:
    permalink: /:collection/:year/:month/:day/:title
    output: true
  articles:
    permalink: /:collection/:year/:month/:day/:title
    output: true
  project:
    permalink: /:collection/:year/:month/:day/:title
    output: true

defaults:
  -
    scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "project"
    values:
      layout: "post"      